### PR TITLE
Don't assume anything about cwd

### PR DESCRIPTION
**Pull request by jwilk**
Fixes:

    FileNotFoundError: [Errno 2] No such file or directory: 'lib/html/en.css'

when current working directory is not the source root directory.

### CODE REVIEW

**Comment by 5j9** [comment]
Failed on toolforge with the following error:
```
*** Starting uWSGI 2.0.7-debian (64bit) on [Fri Sep  6 04:56:55 2019] ***
compiled with version: 4.9.2 on 17 March 2018 15:40:38
os: Linux-4.9.0-0.bpo.6-amd64 #1 SMP Debian 4.9.88-1+deb9u1~bpo8+1 (2018-05-13)
nodename: permission-denied-test-1438133923-9z9ta
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /data/project/permission-denied-test
detected binary path: /usr/bin/uwsgi-core
your memory page size is 4096 bytes
detected max file descriptor number: 65536
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :8000 fd 3
Python version: 3.4.2 (default, Oct  8 2014, 10:47:48)  [GCC 4.9.1]
PEP 405 virtualenv detected: /data/project/permission-denied-test/www/python/venv
Set PythonHome to /data/project/permission-denied-test/www/python/venv
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1f2d3a0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 363840 bytes (355 KB) for 4 cores
*** Operational MODE: preforking ***
mounting /data/project/permission-denied-test/www/python/src/app.py on /permission-denied-test
Traceback (most recent call last):
  File "/data/project/permission-denied-test/www/python/src/app.py", line 37, in <module>
    from lib.html.fa import (
  File "./lib/html/fa.py", line 16, in <module>
    CSS = open(htmldir / 'fa.css', 'rb').read()
TypeError: invalid file: PosixPath('lib/html/fa.css')
```

I believe it's because Python 3.4's `open` does not support path-like objects, the support was added in 3.6. Apparently [the latest Python version that toolforge supports is 3.5](https://wikitech.wikimedia.org/wiki/Help:Toolforge/Web#python3.5_(Python3_+_Kubernetes)).

**Comment by jwilk** [comment]
Ouch. README implies you need Python 3.6+, so I didn't test with anything earlier.

**Comment by 5j9** [comment]
Yeah, sorry about that. README needs to be updated. Initially citer only supported 3.6+, but installing and maintaining a new version of Python on Toolforge turned out to cause much more headaches than I had anticipated... Currently citer is 3.4-compatible and using the default Kubernetes image for Python on Toolforge.

**Comment by jwilk** [comment]
OK, I ditched `pathlib` in favor of `os.path`.
I also made the log file location independent of cwd.

**Comment by 5j9** [comment]
Are you sure that you've pushed all your changes? I don't see any reference to `os.path` in the changed lines, it seems that the patch is still using `pathlib.Path`.

**Comment by jwilk** [comment]
Oops, I pushed the wrong commit. Fixed now.

**Comment by 5j9** [comment]
Thank you!

**Pull request merged**
